name: not_static_icons
description: "Beautifully crafted animated icons for Flutter, crafted with Lucide â€” no Rive or Lottie required."
version: 0.27.0
homepage: https://github.com/khlebobul/not_static_icons

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  path: ^1.9.1
